# Generated by Django 2.2.6 on 2019-11-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.TextField()),
                ('model', models.TextField()),
                ('build_date', models.DateField()),
                ('storage_capacity', models.PositiveIntegerField()),
                ('isEnterpriseModel', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
