# Generated by Django 2.2.6 on 2019-11-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_auto_20191105_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='vendor',
            field=models.TextField(choices=[('Apple', 'Apple'), ('HP', 'HP'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo')]),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
