# Generated by Django 2.2.6 on 2019-11-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_auto_20191105_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='storage_capacity',
            new_name='storage_capacity_GB',
        ),
    ]
